language: java

sudo: false
os:
  - osx
jdk:
  - openjdk11

env:
  global:
    # OSSRH_JIRA_USERNAME
    - secure: "ZbXlqCROOJJFHsb+sEBzbwfbPPIMAz3eohlBV68Fe7DTpPvDnQm6ylFVbuSzz317DPSKQGPUkUafgSO3il5OuOxli0TiXtZOdiIaM6L9Cm9AC5ACfN1rSR0lgK/4DKYqB2g87tPtlgV7DQazLAc+NuVoTJbRoVZox3BCB9f+RS9xujqIz4caGkyfOjHbjkmu2QVcJ0nQBnFf2SNwtysVQpFMfA4o+B13tfwS/CDGFSK44rNmStNy7FyZS5VTW4yz+Eqnw0M1r5U8ApXiqz02kvEeXX8AXGUwwOipkVg5LDJAUbssKxn6/L4F0zfpsjADUUiUGg9eq7DzCS2a0MS/pVULB8s3MWN9hyew+QdoGPtwf9krbmHKHd1zwkmKz9eKD2hgIcYnoQAMObH1WQs7YKfgZ3YyzWTgNcsnsy29DANCH3nrY5UF5NIl0vF+kBNWky0LduUOKiTEjgVsVhqHg+cgiNE1Y3Mj+KIT40M/T91L9k1EJheBwsI2opiraYwTPdZYDU0eQmRYb38T4Ey3kmhuNkesKd3F6FthvxjwypS/lcm9zdBsFaq+8+vGbQR3pNhRGFDvkUAwZx/P8AL7F7UGyRcNVixs5ibIt3UEGDNzLku38BVWSCzCygTaQlxp6VQfV/fFk1AhAF9svpJlC/tN01/P61fZvUgd5m5xECw="
    # OSSRH_JIRA_PASSWORD
    - secure: "D1MT/FptXdzTCsDK71O9j+Eqgf8zofWZ9T3I+zBorCIy0M4H8cRYFVkSCSK6KwUgonXyid9+Z3UdOLedL45gYTMWU1RiVDgao9IoEXbef1tvjvX8Qda3qPNXY5tI3LpBeq65Ss+9ORXjKKWy2MKj7s+s3l1+GFMn0RBngQWNLKzqcAQuc0SW/72rEWKdouMhqtFdKjUw0dm0a0S4W2rYKPDhsLEQPPSu5jFCNp90RxSwy/ZPQvmjuv3L2kbGiIMMckmo2YGYw3SgiMzP+RuDM7bWcqNewKqrnhWnKl8rcL9qHb+gZsAcHzKa3yhrvEILLt3iTb59itRw5iLOKjXIdfON8ZlSfe8TatjYxtDmCyL+vqj7jcKvA52T0l7vvkX5ye3p+rOAaymyIbYefkSWkxM2AqdNRJI7vrF4uj2hcyrowSz4FTLqLHgeDZP+cz8Y1kx8xuxaWelxJ8WPE5Sn70XCeBnNpmaSBvpsdWzYKJW5THQwNqnbhBwUcCFKTt834Y8hcnyeduBa7EAxFw1pboXm9gkVNg6e+4p+Za0xAEMYNr5uRW2/6VZs0ViYZimIoS33JRSzHpQalwUN9KQl0R3qDQ9cOqsB23DHva+br0/0yAuSc7JmkNhy/b2p6cY0tQvnYLzgwDxo3lQC5cBUhPtdX+NhviknDQk8aM4Y66I="
    # GPG_KEY_NAME
    - secure: "L6W7bG2wftIDniwnlAyYbX7Lz3Wvlz0zVCI5G16J2ZiSJwYQa2tplOzCuikNEOtAzzaAmOyiP1sxfAnlK7WXnq2D3Lzg85iMOVoUo7OR/JW3KI/PMbiy3AXO9k7oQSK5hUTEnGx9BQKhpuLdGiv9hfxaVJXUi8e7RdzDCtMaPo/EnBOBjYGXsVpoHPuUvvOfhOOZNn+t6sGsV8TjOSx7Zg1FEgWBx4dMVhy5y/H3pN4qoDNe8H9Lq7oyE6iPqfyFfTTLfVvZv+pI3tebuSwgtOLJNVq95Yp0qOU4nw5UU+7ooeWLc+A2qLs4UNCG3Z8SdF7BSx+WGkniQnBvCq9HbDvgVzNBChJZqhebBb3VF438pEmdk1EYr8e9aQeP3auiRCqiYsubt85wHw4qYrw6h/gNG/C5baWMzZ9w8MjGEOfFyHQmIKyHoOKHQoAMrNw4+DOVQdJhwvF5a2fHKKpuGIr4kcFNui34azVuPBDIDVljOrnYq5esaxP4mHKxWcWPGJ3s/rSZvkm8C9V1Rs9eWJpfW1/bgICsRFKdOEtMzVVWzlzRvap4N3yvPhX4wI/sdbh1+UKf555+mAuR4+XzXAKqUb8kPdKvOi2qoJFek5GD/GYa7JzMSecD5GYfGWRDJB04W/w5jWNV79zjrFFYGgXuzYc6YETvqibFmalcvo0="
    # GPG_PASSPHRASE
    - secure: "wPz9dmm3H0FfG/V7F6yhYMoro/wChqLM8ZZNwFk4PSUsFZ75rRY6oIPIXTvmnpi9lWkKZ5uPNyXkRwpTNn6weR3oJOPU5SyUUNfQnVYUCY8mbqpWaxjmCwuJ7HB+cMsB+O25s5s3MEt4OkWIDaOte75Thgu+fpVyPLka1Bh5a/bbtfLxSsfi+3CiFQp8+W0ge1mc73GDX2y62Ryoz0w6lRooo03q0s/ySjXKVh5hfa3CIZucCTZnx+243HWtlvOLqK8WD8GOjDX9dng2NeV7dKBtxSAsAKC0v4yhJJCkV4H7XPoTPRrZ806QzCa3SB1e+bElQsyQwDLanHI69gMPlyHk976q/L2LnQgRWEp9JOD69b6FSzx9zkd8Et2//Vqx9jQPCxtWU/NrpjaV/znOl+Q7iSybOD9Th5X85NktKqO9IJaHF6wlZ74a5NHUXTAWy1FD84JLsLF713Ttl1h09/Gab1U+hTiiVm7b7aMJmGWrsl/FLNjHDrYld+Q0yn6fXeuVU4MC+GqD7RQWacP1j4xtpnc2w9kglXC2DGxBDeE0tuesNvoWv0nUmI1vKIIg9tWkdOA88PNj+hXLq7SL9ZMFMO4bz5JhUksmIK6oMYn4c/ySRYM/o7FSpyvwV8KbuyY/6ZKEWvWFGUW1P45bhUJ3std05krn4gx78k8mnXc="
stages:
  - name: deploy
    if: branch = master

after_success:
  - >-
    test $TRAVIS_BRANCH = "master" &&
    ./cd/before-deploy.sh &&
    ./gradlew --version &&
    ./gradlew --info publish
    -PjiraUsername=$OSSRH_JIRA_USERNAME
    -PjiraPass=$OSSRH_JIRA_PASSWORD
    -Psigning.keyId=$GPG_KEY_NAME
    -Psigning.password=$GPG_PASSPHRASE
